version: '3'
services:
  odoo:
    image: odoo:16.0
    env_file: .env
    depends_on:
      - database
    ports:
      - "8069:8069"
    volumes:
      - data:/var/lib/odoo
      - ./custom_addons:/opt/odoo/customaddons
      - ./odoo.conf:/etc/odoo/odoo.conf
    command: --update all

  database:
    image: postgres:15
    env_file: .env
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    command: -p 5432

    ports:
      - "5432:5432"


volumes:
  data:
  db: